django_portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from my_portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='Home'),
    path('blog/', include('my_blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/urls.py
from django.urls import path
from . import views

app_name = "blog_app"

urlpatterns = [
    path('', views.Blog, name='Blog'),
    path('<int:blog_id>', views.Details, name="Details"),
]

my_blog/models.py
from django.db import models


class MyBlogs(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    image = models.ImageField(upload_to='my_blog/images')
    url = models.URLField(blank=True)
    date = models.DateField(auto_now=True)

my_portfolio/models.py
from django.db import models


class MyProjects(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='my_portfolio/images')
    url = models.URLField(blank=True)

my_blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import MyBlogs


def Blog(request):
    myblog = MyBlogs.objects.all()
    context = {
        'blogs': myblog
    }

    return render(request, 'blog.html', context)


def Details(request, blog_id):
    details = get_object_or_404(MyBlogs, pk=blog_id)
    context = {
        'detail': details
    }
    return render(request, 'blog_details.html', context)

my_portfolio/views.py
from django.shortcuts import render
from .models import MyProjects


def Home(request):
    myproject = MyProjects.objects.all()
    context = {
        "projects": myproject
    }
    return render(request, 'index.html', context)

templates/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blogs</title>
    {#    Bootsrtap CSS#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>

<div class="container-fluid text-center">

    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand">Blog</a>
        <form class="form-inline">
            <a href="{% url 'Home' %}" class="btn btn-success">Portfolio</a>
            {#      <a href="{% url 'blog_app:Blog' %}" class="btn btn-outline-danger">Blog</a>#}
        </form>
    </nav>
    <div class="row row-cols-3">
        {% for blog in blogs %}
            <div class="col">
                <a href="{% url 'blog_app:Details' blog.id %}">
                    <h3>{{ blog.title }}</h3>
                </a>
                <h6>{{ blog.date }}</h6>
                <img src="{{ blog.image.url }}" height="100px" width="150px" alt="img">

            </div>
        {% endfor %}
    </div>

</div>


</body>
</html>

templates/blog_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog Details</title>
    {#    Bootsrtap CSS#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>


<div class="container-fluid text-center">
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand">Blog Details</a>
        <form class="form-inline">
            <a href="{% url 'Home' %}" class="btn btn-success">Portfolio</a>
            <a href="{% url 'blog_app:Blog' %}" class="btn btn-outline-danger">Blog</a>
        </form>
    </nav>


    <h2>
        {{ detail.title }}
    </h2>
    <p>{{ detail.date }}</p>
    <img src="{{ detail.image.url }}" alt="img" width="250px" height="200">
    <br>
    <br>
    <br>
    <p>
        {{ detail.description }}
    </p>

    {% if detail.url %}
        <a href="{{ detail.url }}">Click Here</a>
    {% endif %}

</div>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Portfolio</title>
    {#    Bootsrtap CSS#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
{% load static %}
<div class="container-fluid text-center">
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand">Portfolio</a>
        <form class="form-inline">
            <a href="{% url 'blog_app:Blog' %}" class="btn btn-outline-danger">Blog</a>
        </form>
    </nav>
    <img src="{% static 'portfolio/75348368.webp' %}" alt="img" height="150px" width="200px">

    <h4>Hi There I'm Samrat. I'm trying to build a webpage using Django(Just for learning).</h4>

    <h5>Here is Some of My Projects</h5>

    <div class="row row-col-3">
        {% for project in projects %}
            <div class="col">
                <h2> {{ project.title }}</h2>
                <a href="{{ project.url }}">
                    <img src="{{ project.image.url }}" height="250px" width="300px">
                </a>
                <p>{{ project.description }}</p>
            </div>
        {% endfor %}
    </div>


</div>


</body>
</html>